### ISSUE TITLE
gallery

### ISSUE THREAD

**Issue by adhilsalim** [tedxajce/tedx2024#6]

**Comment by adhilsalim** [comment]
![100](https://github.com/tedxajce/tedx2024/assets/69722917/5884eef9-3626-40ae-ae50-0e0788b2cf3a)
![101](https://github.com/tedxajce/tedx2024/assets/69722917/8a013450-ca27-49ab-97c1-20262983c039)
![102](https://github.com/tedxajce/tedx2024/assets/69722917/178219e6-2d85-44ec-9a37-a22391a8a96b)
![103](https://github.com/tedxajce/tedx2024/assets/69722917/9dc643c2-ec3e-433f-9b49-caf2c1336179)
![104](https://github.com/tedxajce/tedx2024/assets/69722917/2cbc010d-1f6b-428d-9fac-90cf7ddf58af)
![105](https://github.com/tedxajce/tedx2024/assets/69722917/8d97597e-f6a2-4169-a90b-16765eb3675c)
![106](https://github.com/tedxajce/tedx2024/assets/69722917/39e4a725-2ac1-42ad-902c-d901be0ef422)
![107](https://github.com/tedxajce/tedx2024/assets/69722917/a803416c-c13f-4b1d-978b-e418ccc5b41a)
![108](https://github.com/tedxajce/tedx2024/assets/69722917/bb7ecad7-2ac6-4d99-a5b7-400b6dacd021)
![109](https://github.com/tedxajce/tedx2024/assets/69722917/d05cd95f-9823-449f-8cb0-7d5288b653dd)
![110](https://github.com/tedxajce/tedx2024/assets/69722917/f782d052-00db-4042-8d82-4b530c73062c)

**Comment by adhilsalim** [comment]
Should this be closed? @zameel7

**Comment by zameel7** [comment]
Yep! We just want the links thats it. It won’t go away.

**Comment by adhilsalim** [comment]
not raising PR since the previous commit 61961c8362d5082894e252aa50afce8dba4b78f5 is already merged. @zameel7 
You may close this issue if opened.
